import type { Metadata } from "next";
import { Poppins, Abril_Fatface } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import Navbar from "@/components/layoutBlocks/navbar/Navbar";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500'],
  variable: '--font-poppins',
});

const abril = Abril_Fatface({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-abril',
});

export const metadata: Metadata = {
  title: {
    template: '%s | MyFairBanking',
    default: 'Home | MyFairBanking',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  font-sans`}>
        <Providers>
          {children}
        </Providers>
        <Navbar />
      </body>
    </html>
  );
}
